version: '3'
services:
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    ports:
      - "3000:8081"

  server-socket-io:
    image: socket.io-server:staging
    container_name: server-socket-io
    volumes:
      - ./server:/usr/src/app
    #command: [/usr/src/app/entrypoint.sh]
    ports:
      - "2000:3000"
  
  client-socket-io:
    image: socket.io-client:staging
    container_name: client-socket-io
    volumes:
      - ./client:/usr/src/app
    #command: [entrypoint.sh]
    ports:
      - "8080:3000"
  

